
---
title: "Project 5 - Movies Domestic % Gross"
author: "Generated by ChatGPT"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

## Import the Data Set
```{r}
# Import the data set
movies <- read.csv(file.choose(), stringsAsFactors = TRUE)
```

## Data Exploration
```{r}
# Explore the data
head(movies)
tail(movies)
summary(movies)
str(movies)
```

## Load Required Libraries
```{r}
# Load tidyverse package
library(tidyverse)
```

## Filter Data by Genre
```{r}
# Filter the data for selected genres
filt <- (movies$Genre == "action") | (movies$Genre == "adventure") | (movies$Genre == "animation") | 
        (movies$Genre == "comedy") | (movies$Genre == "drama")
movies2 <- movies[filt,]
movies2
```

## Filter Data by Studio
```{r}
# Filter the data for selected studios
filt2 <- movies$Studio %in% c("Buena Vista Studios", "WB", "Fox", "Universal", "Sony", "Paramount Pictures")   
movies2 <- movies[filt & filt2,]
movies2
```

## Structure of Filtered Data
```{r}
# Display structure of filtered data
str(movies2)
```

## Plotting Domestic Gross % by Genre
```{r}
# Lay the foundation for the plot's data and aesthetic layers
p <- ggplot(data = movies2, aes(x = Genre, y = Gross...US))
p
```

### Add Geometries
```{r}
# Add points and boxplot with jitter
p + geom_point()
q <- p + geom_jitter(aes(size = Budget...mill., colour = Studio)) + 
        geom_boxplot(alpha = 0.7, outlier.colour = NA)
q
```

## Add Labels and Title
```{r}
# Add non-data ink: labels and title
q <- q + xlab("Genre") + ylab("Gross % US") + 
        ggtitle("Domestic Gross % by Genre") + 
        theme(plot.title = element_text(hjust = 0.5))
q
```

## Final Touches
```{r}
# Adjust size label
q$labels$size <- "Budget $M"
q
```
